AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test

  Sample SAM Template for test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CfbdDataIngestionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cfbd_data/
      Handler: app.cfbd_data_ingestion
      Runtime: python3.9
      Timeout: 900
      MemorySize: 128
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: Cfbds3ArchiveAccessPolicy
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource: arn:aws:s3:::cfbd-data-archive/*
        - Statement:
            - Sid: CfbdSecretManagerAccess
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:us-east-1:430738663938:secret:prod/cfbd/apiKey-ZRZ1c3
      Environment:
        Variables:
          s3_destination: cfbd-data-archive
          secret_name: prod/cfbd/apiKey
          secret_region: us-east-1
      Layers:
        - !Ref libs
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1

  DataIngestionWrapperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cfbd_data/
      Handler: app.cfbd_ingestion_wrapper
      Runtime: python3.9
      Timeout: 900
      MemorySize: 128
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: CfbdIngestionInvokePolicy
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt CfbdDataIngestionFunction.Arn
      Environment:
        Variables:
          CfbdFunction: !GetAtt CfbdDataIngestionFunction.Arn
      Layers:
        - !Ref libs
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1
  ApplyPredictionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cfbd_data/
      Handler: app.apply_prediction
      Runtime: python3.9
      Timeout: 900
      MemorySize: 360
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: Cfbds3ArchiveAccessPolicy
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource: arn:aws:s3:::cfbd-data-archive/*
      Environment:
        Variables:
          s3_source_bucket: cfbd-data-archive
          betting_lines_file: CFBD_Analysis/BettingApi_get_lines_data_extract.txt
          games_data_file: CFBD_Analysis/GamesApi_get_games_data_extract.txt
          team_game_stats_file: CFBD_Analysis/GamesApi_get_team_game_stats_data_extract.txt
          player_season_stats_file: CFBD_Analysis/PlayersApi_get_player_season_stats_data_extract.txt
          transfer_portal_file: CFBD_Analysis/PlayersApi_get_transfer_portal_data_extract.txt
          recruiting_groups_file: CFBD_Analysis/RecruitingApi_get_recruiting_groups_data_extract.txt
          recruiting_players_file: CFBD_Analysis/RecruitingApi_get_recruiting_players_data_extract.txt
          advanced_team_game_stats_file: CFBD_Analysis/StatsApi_get_advanced_team_game_stats_data_extract.txt
          fbs_teams_file: CFBD_Analysis/TeamsApi_get_fbs_teams_data_extract.txt
          roster_data_file: CFBD_Analysis/TeamsApi_get_roster_data_extract.txt
          output_file: CFBD_Analysis/output/output_prediction.txt
      Layers:
        - !Ref libs
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1

  PredictionOutputFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cfbd_data/
      Handler: app.prediction_output
      Runtime: python3.9
      Timeout: 900
      MemorySize: 128
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: Cfbds3ArchiveAccessPolicy
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource: arn:aws:s3:::cfbd-data-archive/*
      Environment:
        Variables:
          s3_source_bucket: cfbd-data-archive
          output_prediction_file: CFBD_Analysis/output/output_prediction.txt
      Events:
        PredictionOutput:
          Type: Api
          Properties:
            Path: /prediction_output
            Method: get
      Layers:
        - !Ref libs
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1

  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: cfbd-analytics-packages-general
      Description: Lambda layer with libs like pandas and datetime
      ContentUri: libs

  S3DataExtract:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'cfbd-data-archive'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'

  # Web Platform Infrastructure Resources
  GameLineAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Description: A simple CORS compliant API
      Name: GameLineAPI
      EndpointConfiguration:
        Types:
          - REGIONAL

  # The Resource (/hello) of our API
  GameLineAPIResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt
        - GameLineAPI
        - RootResourceId
      PathPart: hello
      RestApiId: !Ref GameLineAPI

  # The method to call (GET) for our API
  GameLineAPIGETMethod:
    Type: 'AWS::ApiGateway::Method'
    #checkov:skip=CKV_AWS_59: "This API does not expose backend service"
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        Type: MOCK
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: "{\n \"statusCode\": 200\n}"
        IntegrationResponses:
          - StatusCode: 200
            SelectionPattern: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: '''*'''
            ResponseTemplates:
              application/json: "{\"message\": \"Hello World!\"}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
          ResponseModels:
            application/json: Empty
      RestApiId: !Ref GameLineAPI
      ResourceId: !Ref GameLineAPIResource

  # A deployment resource for deploying our API
  Deployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - GameLineAPIGETMethod
    Properties:
      RestApiId: !Ref GameLineAPI
      StageName: v1

  # The Amazon S3 bucket into which our Single Page Application build files must be deployed
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'react-cors-spa-${GameLineAPI}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: s3-access-logs
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'

  # The Amazon S3 bucket policy for securing the bucket hosting the application
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PolicyForCloudFrontPrivateContent
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CFOriginAccessIdentity.S3CanonicalUserId
            Action: 's3:GetObject*'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket

  # The Amazon S3 bucket into which access logs from S3 (for the application) and CloudFront will be put
  LoggingBucket:
    #checkov:skip=CKV_AWS_18: "This bucket is private and only for storing logs"
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'react-cors-spa-${GameLineAPI}-logs'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      AccessControl: LogDeliveryWrite
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
    DeletionPolicy: Delete

  # The Amazon CloudFront distribution exposing our Single Page Application
  CFDistribution:
    #checkov:skip=CKV_AWS_68: "For demo purposes and to reduce cost, no WAF is configured"
    Type: 'AWS::CloudFront::Distribution'
    DependsOn:
      - CFOriginAccessIdentity
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt S3Bucket.RegionalDomainName
            Id: myS3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CFOriginAccessIdentity}"
        Enabled: 'true'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: myS3Origin
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # CORS-S3Origin
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        Logging:
          Bucket: !GetAtt LoggingBucket.RegionalDomainName
          Prefix: 'cloudfront-access-logs'
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: 'TLSv1.2_2021'

  # The Amazon CloudFront origin access identity
  CFOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    DependsOn:
      - S3Bucket
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'access-identity-react-cors-spa-${GameLineAPI}'



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CfbdDataIngestionFunction:
    Description: "College Football Data Ingestion Function ARN"
    Value: !GetAtt CfbdDataIngestionFunction.Arn
  DataIngestionWrapperFunction:
    Description: "Data Ingestion Wrapper Function ARN"
    Value: !GetAtt DataIngestionWrapperFunction.Arn
  PredictionOutputFunction:
    Description: "API Prediction Output Function ARN"
    Value: !GetAtt PredictionOutputFunction.Arn
  WebAPIEndpoint:
    Value: !Sub "https://${GameLineAPI}.execute-api.${AWS::Region}.amazonaws.com/v1/hello"
  WebBucketName:
    Value: !Sub "react-cors-spa-${CFOriginAccessIdentity}"
